# Generated by Django 5.1.4 on 2024-12-31 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0002_credittransaction_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credittransaction',
            name='invoice_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='stripe_invoice_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
