# Generated by Django 5.1.4 on 2024-12-26 19:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='promotions/')),
                ('link_type', models.CharField(choices=[('internal', 'Internal Link'), ('external', 'External URL')], default='internal', max_length=10)),
                ('external_url', models.URLField(blank=True, help_text='Use this for external links', null=True)),
                ('internal_name', models.CharField(blank=True, help_text='Name of the internal URL pattern', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Lower numbers will be displayed first')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'ordering': ['order', '-start_date'],
            },
        ),
    ]
