# Generated by Django 5.1.4 on 2024-12-31 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
    ]
