# Generated by Django 5.1.4 on 2025-01-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_create_initial_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='external_url',
            field=models.URLField(blank=True, help_text='Use this for external links (e.g., https://example.com)', null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='internal_name',
            field=models.CharField(blank=True, help_text="Name of the URL pattern (e.g., 'tools:school_finder', 'news:detail'). You can find this in your urls.py files as the 'name' parameter.", max_length=100, null=True),
        ),
    ]
