
services:
  web:
    build: .
    command: /start.sh
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=travelTAF.settings
      - ALLOWED_HOSTS=localhost,127.0.0.1,192.168.0.65
    networks:
      - travelTAF_network

  nginx:
    image: nginx:alpine
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - travelTAF_network

networks:
  travelTAF_network:
    driver: bridge

volumes:
  static_volume:
  media_volume: 