# Generated by Django 5.1.4 on 2024-12-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='content',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
        migrations.AddField(
            model_name='news',
            name='content_blocks',
            field=models.JSONField(default=list, help_text='Structured content blocks'),
        ),
        migrations.AddField(
            model_name='news',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/featured/'),
        ),
        migrations.AddField(
            model_name='news',
            name='source_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='news',
            name='source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='news',
            name='summary',
            field=models.TextField(blank=True, help_text='A brief introduction or summary of the article'),
        ),
    ]
