# Generated by Django 5.1.4 on 2025-04-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_dialogcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='send_as_newsletter',
            field=models.BooleanField(default=False, help_text='If checked, this article will be included in the next newsletter'),
        ),
    ]
