# Generated by Django 5.1.4 on 2024-12-16 18:49

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_news_content_remove_news_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='content_blocks',
        ),
        migrations.AddField(
            model_name='news',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Content'),
            preserve_default=False,
        ),
    ]
