# Generated by Django 5.1.4 on 2024-12-27 18:40

import django.db.models.deletion
import resume_builder.models
import storages.backends.gcloud
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='ats_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resume',
            name='job_description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='resume',
            name='optimized_content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='resume',
            name='original_content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='resume',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, storage=storages.backends.gcloud.GoogleCloudStorage(), upload_to=resume_builder.models.resume_pdf_path),
        ),
        migrations.AlterField(
            model_name='resume',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL),
        ),
    ]
