# Generated by Django 5.1.4 on 2025-02-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='icon',
            field=models.TextField(blank=True, help_text='SVG icon markup'),
        ),
    ]
