# Generated by Django 5.1.4 on 2025-01-01 20:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=20)),
                ('origin', models.CharField(max_length=5)),
                ('destination', models.CharField(max_length=5)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('DELAYED', 'Delayed'), ('DEPARTED', 'Departed'), ('ARRIVED', 'Arrived'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('provider_name', models.CharField(max_length=50)),
                ('provider_reference', models.CharField(max_length=100)),
                ('provider_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['flight_number'], name='flights_fli_flight__794da4_idx'), models.Index(fields=['departure_time'], name='flights_fli_departu_5bc2af_idx'), models.Index(fields=['provider_reference'], name='flights_fli_provide_3381c6_idx')],
            },
        ),
        migrations.CreateModel(
            name='FlightBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], max_length=20)),
                ('booking_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('provider_booking_id', models.CharField(max_length=100)),
                ('provider_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flights.flight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookingPassenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(blank=True, max_length=10)),
                ('checked_in', models.BooleanField(default=False)),
                ('boarding_pass_issued', models.BooleanField(default=False)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flightbooking')),
            ],
        ),
        migrations.CreateModel(
            name='PassengerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('passenger_type', models.CharField(choices=[('ADULT', 'Adult'), ('CHILD', 'Child'), ('INFANT', 'Infant')], max_length=10)),
                ('passport_number', models.CharField(max_length=50, unique=True)),
                ('passport_expiry', models.DateField()),
                ('nationality', models.CharField(max_length=2)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('special_requirements', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='passengers',
            field=models.ManyToManyField(through='flights.BookingPassenger', to='flights.passengerdetail'),
        ),
        migrations.AddField(
            model_name='bookingpassenger',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flights.passengerdetail'),
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=5)),
                ('destination', models.CharField(max_length=5)),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('passengers', models.JSONField(default=dict)),
                ('search_params', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='passengerdetail',
            index=models.Index(fields=['passport_number'], name='flights_pas_passpor_e5279b_idx'),
        ),
        migrations.AddIndex(
            model_name='passengerdetail',
            index=models.Index(fields=['created_by'], name='flights_pas_created_ad21c9_idx'),
        ),
        migrations.AddIndex(
            model_name='flightbooking',
            index=models.Index(fields=['booking_reference'], name='flights_fli_booking_7aef09_idx'),
        ),
        migrations.AddIndex(
            model_name='flightbooking',
            index=models.Index(fields=['booking_date'], name='flights_fli_booking_16f4ca_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bookingpassenger',
            unique_together={('booking', 'passenger')},
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['user', '-created_at'], name='flights_sea_user_id_d2fc7e_idx'),
        ),
    ]
