# Generated by Django 5.1.4 on 2025-01-01 22:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VacationSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.CharField(max_length=255)),
                ('travel_dates', models.JSONField()),
                ('budget_range', models.CharField(max_length=50)),
                ('travelers', models.IntegerField()),
                ('search_results', models.JSONField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['search_id'], name='main_vacati_search__d9a413_idx'), models.Index(fields=['created_at'], name='main_vacati_created_893022_idx')],
            },
        ),
    ]
