# Generated by Django 5.1.4 on 2025-04-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(help_text="Two-letter country code (e.g., 'CA' for Canada)", max_length=2, unique=True)),
                ('flag', models.ImageField(help_text='Destination flag image', upload_to='destination_flags/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show this destination in the featured section')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which to display the destination')),
                ('feature1_icon', models.CharField(help_text='SVG path or icon class', max_length=50)),
                ('feature1_text', models.CharField(max_length=100)),
                ('feature2_icon', models.CharField(help_text='SVG path or icon class', max_length=50)),
                ('feature2_text', models.CharField(max_length=100)),
                ('feature3_icon', models.CharField(help_text='SVG path or icon class', max_length=50)),
                ('feature3_text', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Travel Destination',
                'verbose_name_plural': 'Travel Destinations',
                'ordering': ['order', 'name'],
            },
        ),
    ]
