# Generated by Django 5.1.4 on 2025-01-31 11:56

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tools', '0007_alter_visarelationship_citizenship_country_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImmigrationProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description')),
                ('eligibility_criteria', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Eligibility Criteria')),
                ('benefits', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Benefits')),
                ('application_process', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Application Process')),
                ('featured_image', models.ImageField(blank=True, null=True, storage='storages.backends.gcloud.GoogleCloudStorage', upload_to='immigration_images/')),
                ('deadline', models.DateField(blank=True, null=True)),
                ('official_link', models.URLField(blank=True, null=True)),
                ('chat_enabled', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, help_text='Feedback for rejected programs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_programs', to=settings.AUTH_USER_MODEL)),
                ('country', models.ForeignKey(help_text='The country this immigration program belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='immigration_programs', to='tools.countries')),
            ],
            options={
                'verbose_name_plural': 'Immigration Programs',
                'ordering': ['-created_at'],
            },
        ),
    ]
