# Generated by Django 5.1.4 on 2025-01-31 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immigrationprograms', '0001_initial'),
        ('tools', '0007_alter_visarelationship_citizenship_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immigrationprogram',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immigration_programs', to='tools.countries'),
        ),
    ]
