# Generated by Django 5.1.4 on 2025-02-01 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immigrationprograms', '0002_alter_immigrationprogram_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immigrationprogram',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
