# Generated by Django 5.1.4 on 2025-03-05 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immigrationprograms', '0003_alter_immigrationprogram_slug'),
        ('tools', '0008_alter_visarelationship_documents_required_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.countries')),
            ],
            options={
                'verbose_name': 'Featured Country',
                'verbose_name_plural': 'Featured Countries',
                'ordering': ['order'],
            },
        ),
    ]
