# Generated by Django 5.1.3 on 2024-12-07 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Document Management', max_length=255)),
            ],
            options={
                'verbose_name': 'Document Management',
                'verbose_name_plural': 'Document Management',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('chat', 'Chat Message'), ('call', 'Call Request')], help_text='The type of interaction (chat message or call request)', max_length=10)),
                ('message', models.TextField(blank=True, help_text="The user's message or call details", null=True)),
                ('response', models.TextField(blank=True, help_text="The system's response to the user's message", null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='The current status of the interaction', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the interaction was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the interaction was last modified')),
                ('user', models.ForeignKey(blank=True, help_text='The user who initiated the interaction. Can be null for anonymous users.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Interaction',
                'verbose_name_plural': 'User Interactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['type'], name='agent_inter_type_3964a7_idx'), models.Index(fields=['status'], name='agent_inter_status_8538a6_idx'), models.Index(fields=['created_at'], name='agent_inter_created_4846e0_idx'), models.Index(fields=['user'], name='agent_inter_user_id_c21cdb_idx')],
            },
        ),
    ]
