# Generated by Django 5.1.4 on 2024-12-29 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['name'], 'verbose_name': 'Subscription Plan', 'verbose_name_plural': 'Subscription Plans'},
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='duration_type',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='price',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='stripe_price_id',
        ),
        migrations.CreateModel(
            name='PlanDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('duration_type', models.CharField(choices=[('ONE_TIME', 'One Time'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('SEMI_ANNUAL', 'Semi-Annual'), ('YEARLY', 'Yearly')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in USD', max_digits=10)),
                ('stripe_price_id', models.CharField(blank=True, help_text='Stripe Price ID for this duration', max_length=100)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='durations', to='subscriptions.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Plan Duration',
                'verbose_name_plural': 'Plan Durations',
                'ordering': ['plan', 'duration_type'],
                'unique_together': {('plan', 'duration_type')},
            },
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='plan_duration',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='user_subscriptions', to='subscriptions.planduration'),
            preserve_default=False,
        ),
    ]
