# Generated by Django 5.1.4 on 2024-12-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='subscription_type',
            field=models.CharField(choices=[('newsletter', 'General Newsletter'), ('news', 'News Updates')], default='newsletter', max_length=20),
        ),
    ]
