# Generated by Django 5.1.4 on 2025-01-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_alter_countries_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='visatype',
            name='is_eta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visatype',
            name='is_visa_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='visatype',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
