# Generated by Django 5.1.4 on 2025-01-20 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_visatype_is_eta_visatype_is_visa_free_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='visarelationship',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='visatype',
            name='is_eta',
        ),
        migrations.RemoveField(
            model_name='visatype',
            name='is_visa_free',
        ),
        migrations.AddField(
            model_name='visarelationship',
            name='is_eta',
            field=models.BooleanField(default=False, help_text='Check if this requires ETA/eVisa'),
        ),
        migrations.AddField(
            model_name='visarelationship',
            name='is_visa_free',
            field=models.BooleanField(default=False, help_text='Check if this is a visa-free arrangement'),
        ),
        migrations.AlterField(
            model_name='visarelationship',
            name='citizenship_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visa_from', to='tools.country'),
        ),
        migrations.AlterField(
            model_name='visarelationship',
            name='destination_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visa_to', to='tools.country'),
        ),
        migrations.RemoveField(
            model_name='visarelationship',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='visarelationship',
            name='valid_until',
        ),
    ]
