# Generated by Django 5.1.4 on 2025-01-20 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_alter_visarelationship_is_eta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visarelationship',
            name='citizenship_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visa_from', to='tools.countries'),
        ),
        migrations.AlterField(
            model_name='visarelationship',
            name='destination_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visa_to', to='tools.countries'),
        ),
    ]
