# Generated by Django 5.1.4 on 2025-02-07 18:33

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0007_alter_visarelationship_citizenship_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visarelationship',
            name='documents_required',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Documents Required'),
        ),
        migrations.AlterField(
            model_name='visarelationship',
            name='notes',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Notes'),
        ),
    ]
